/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package taller

object App {
  def main(args: Array[String]): Unit = {
    println(greeting())
    val num1 = 32
    val num1 = 64
  }

  def greeting(): String = "Hello, world!"
}
